"""Refresh static SEO metadata. No runtime URL guessing or placeholder domains.

Before deployment, provide the real HTTPS address with --base-url. It is saved
in site-config.json for subsequent runs. Requires lxml and Pillow.
"""
from pathlib import Path
from urllib.parse import urlsplit, urljoin, quote, unquote
from html import escape
import argparse
import json
import re
import xml.etree.ElementTree as ET
from lxml import html
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
START, END = '<!-- Site SEO: generated by tools/prepare_seo.py -->', '<!-- /Site SEO -->'

def normalize_base(value):
    if not value:
        return None
    parsed = urlsplit(value.strip())
    if parsed.scheme != 'https' or not parsed.hostname or parsed.query or parsed.fragment or parsed.username or parsed.password:
        raise ValueError('Podaj pełny docelowy adres HTTPS, bez parametrów i fragmentów.')
    if parsed.hostname in {'localhost', '127.0.0.1'}:
        raise ValueError('Adres lokalny nie jest docelową domeną strony.')
    return value.strip().rstrip('/') + '/'

def public_url(base, path):
    return urljoin(base, quote(unquote(path), safe='/'))

def meta(name, content, kind='property'):
    return f'  <meta {kind}="{name}" content="{escape(str(content), quote=True)}" />'

def page_data(path, source):
    doc = html.fromstring(source)
    title = doc.xpath('//title')[0].text_content().strip()
    description = doc.xpath('//meta[@name="description"]/@content')[0]
    heading = ' '.join(doc.xpath('//h1')[0].text_content().split())
    article = path.name.startswith('wiedza-')
    photo = 'assets/photos/chihuahua-2026/chihuahua-2026-56.jpg'
    alt = 'Szczenię Chihuahua z hodowli Bajeczne Urwisy'
    if path.name in {'index.html', 'maltanczyk.html', 'galeria-maltanczyki.html'}:
        photo, alt = 'assets/photos/g1.jpg', 'Szczenię maltańczyka z hodowli Bajeczne Urwisy'
    elif article or path.name == 'baza-wiedzy.html':
        candidates = doc.xpath('//main//*[contains(@class,"article-visual") or contains(@class,"kb-hub-visual")]//img')
        if candidates:
            photo, alt = candidates[0].get('src'), candidates[0].get('alt', heading)
    if path.name in {'chihuahua.html', 'maltanczyk.html', 'rasy.html'}:
        candidates = doc.xpath('//section[contains(@class,"breed-hero")]//img')
        if candidates:
            photo, alt = candidates[0].get('src'), candidates[0].get('alt', heading)
    if not (ROOT/unquote(photo)).is_file():
        raise ValueError(f'Brak zdjęcia udostępniania dla {path.name}: {photo}')
    return dict(title=title, description=description, heading=heading, article=article, photo=photo, alt=alt, doc=doc)

def seo_block(path, data, config, base):
    title, description = data['title'], data['description']
    organization = {
        '@type': 'Organization', 'name': config['name'], 'telephone': config['telephone'],
        'address': {'@type': 'PostalAddress', 'addressLocality': config['locality'], 'addressRegion': config['region'], 'addressCountry': config['country']},
        'sameAs': config['socialProfiles']
    }
    canonical = public_url(base, '' if path.name == 'index.html' else path.name) if base else None
    if base:
        organization.update({'@id': base+'#organization', 'url': base, 'logo': public_url(base, 'assets/logo-bajeczne-urwisy-clean.png')})
    publisher = {'@id': organization['@id']} if base else {'@type': 'Organization', 'name': config['name']}
    page_type = 'ContactPage' if path.name == 'kontakt.html' else ('CollectionPage' if path.name.startswith(('galeria-', 'baza-wiedzy')) else 'WebPage')
    webpage = {'@type': page_type, 'name': title, 'description': description, 'inLanguage': 'pl-PL'}
    graph = [organization, webpage]
    if base:
        webpage.update({'@id': canonical+'#webpage', 'url': canonical, 'isPartOf': {'@id': base+'#website'}})
        graph.append({'@type': 'WebSite', '@id': base+'#website', 'url': base, 'name': config['name'], 'inLanguage': 'pl-PL', 'publisher': publisher})
    if data['article']:
        article = {'@type': 'Article', 'headline': data['heading'], 'description': description, 'inLanguage': 'pl-PL', 'author': publisher, 'publisher': publisher}
        if base:
            article.update({'@id': canonical+'#article', 'mainEntityOfPage': {'@id': canonical+'#webpage'}, 'image': [public_url(base, data['photo'])]})
            webpage['mainEntity'] = {'@id': canonical+'#article'}
        graph.append(article)
    if base and path.name != 'index.html':
        items = [{'@type': 'ListItem', 'position': 1, 'name': config['name'], 'item': base}]
        if data['article']:
            items.append({'@type': 'ListItem', 'position': 2, 'name': 'Baza wiedzy', 'item': public_url(base, 'baza-wiedzy.html')})
        elif path.name in {'chihuahua.html', 'maltanczyk.html'}:
            items.append({'@type': 'ListItem', 'position': 2, 'name': 'Rasy', 'item': public_url(base, 'rasy.html')})
        items.append({'@type': 'ListItem', 'position': len(items)+1, 'name': data['heading'], 'item': canonical})
        graph.append({'@type': 'BreadcrumbList', '@id': canonical+'#breadcrumb', 'itemListElement': items})
        webpage['breadcrumb'] = {'@id': canonical+'#breadcrumb'}
    tags = [START, meta('robots', 'index, follow, max-image-preview:large', 'name'), meta('og:site_name', config['name']), meta('og:title', title), meta('og:description', description), meta('og:type', 'article' if data['article'] else 'website'), meta('og:locale', 'pl_PL'), meta('twitter:card', 'summary_large_image', 'name'), meta('twitter:title', title, 'name'), meta('twitter:description', description, 'name')]
    if base:
        tags += [f'  <link rel="canonical" href="{escape(canonical, quote=True)}" />', meta('og:url', canonical), meta('og:image', public_url(base, data['photo'])), meta('og:image:alt', data['alt']), meta('twitter:image', public_url(base, data['photo']), 'name'), meta('twitter:image:alt', data['alt'], 'name')]
        with Image.open(ROOT/unquote(data['photo'])) as image:
            tags += [meta('og:image:width', image.width), meta('og:image:height', image.height)]
    payload = json.dumps({'@context': 'https://schema.org', '@graph': graph}, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c')
    tags += ['  <script type="application/ld+json">'+payload+'</script>', END]
    return '\n'.join(tags)

def prepare(base_override=None):
    config_path = ROOT/'site-config.json'
    config = json.loads(config_path.read_text(encoding='utf8'))
    base = normalize_base(base_override or config.get('baseUrl'))
    if base_override:
        config['baseUrl'] = base
        config_path.write_text(json.dumps(config, ensure_ascii=False, indent=2)+'\n', encoding='utf8')
    pages = sorted(ROOT.glob('*.html'))
    for path in pages:
        source = path.read_text(encoding='utf8')
        source = re.sub(re.escape(START)+r'.*?'+re.escape(END)+r'\s*', '', source, flags=re.S)
        source = re.sub(r'\s*<meta\b[^>]*(?:property="og:[^"]*"|name="(?:twitter:[^"]*|robots)")[^>]*>', '', source)
        source = re.sub(r'\s*<link\b[^>]*rel="canonical"[^>]*>', '', source)
        source = re.sub(r'(<meta name="theme-color" content=")[^"]*', r'\g<1>#FBF8F2', source)
        if path.name == 'index.html':
            source = re.sub(r'<title>.*?</title>', '<title>Hodowla Chihuahua i Maltańczyków | Bajeczne Urwisy, Kowalewo Pomorskie</title>', source)
        data = page_data(path, source)
        source = source.replace('</head>', seo_block(path, data, config, base)+'\n</head>')
        path.write_text(source, encoding='utf8')
    prefix = urlsplit(base).path.rstrip('/') if base else ''
    robots = 'User-agent: *\nAllow: /\n'+''.join(f'Disallow: {prefix}/{folder}/\n' for folder in ('_preview', 'tools'))
    if base:
        ET.register_namespace('', 'http://www.sitemaps.org/schemas/sitemap/0.9')
        sitemap = ET.Element('{http://www.sitemaps.org/schemas/sitemap/0.9}urlset')
        for path in pages:
            url = ET.SubElement(sitemap, '{http://www.sitemaps.org/schemas/sitemap/0.9}url')
            ET.SubElement(url, '{http://www.sitemaps.org/schemas/sitemap/0.9}loc').text = public_url(base, '' if path.name == 'index.html' else path.name)
        ET.indent(sitemap, space='  ')
        ET.ElementTree(sitemap).write(ROOT/'sitemap.xml', encoding='utf-8', xml_declaration=True)
        robots += '\nSitemap: '+public_url(base, 'sitemap.xml')+'\n'
    (ROOT/'robots.txt').write_text(robots, encoding='utf8')
    print(json.dumps({'pages': len(pages), 'baseUrl': base, 'status': 'ready-for-deployment' if base else 'domain-required-for-canonical-sitemap-and-social-images'}, ensure_ascii=False))

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--base-url', help='Rzeczywisty docelowy adres HTTPS strony')
    args = parser.parse_args()
    prepare(args.base_url)
